<?php

/* custom routes generated by CRUD */


Route::group(array('prefix' => 'admin/questions/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.questions.'), function () {

Route::get('questions', ['as'=> 'questions.index', 'uses' => 'Questions\QuestionController@index']);
Route::post('questions', ['as'=> 'questions.store', 'uses' => 'Questions\QuestionController@store']);
Route::get('questions/create', ['as'=> 'questions.create', 'uses' => 'Questions\QuestionController@create']);
Route::put('questions/{questions}', ['as'=> 'questions.update', 'uses' => 'Questions\QuestionController@update']);
Route::patch('questions/{questions}', ['as'=> 'questions.update', 'uses' => 'Questions\QuestionController@update']);
Route::get('questions/{id}/delete', array('as' => 'questions.delete', 'uses' => 'Questions\QuestionController@getDelete'));
Route::get('questions/{id}/confirm-delete', array('as' => 'questions.confirm-delete', 'uses' => 'Questions\QuestionController@getModalDelete'));
Route::get('questions/{questions}', ['as'=> 'questions.show', 'uses' => 'Questions\QuestionController@show']);
Route::get('questions/{questions}/edit', ['as'=> 'questions.edit', 'uses' => 'Questions\QuestionController@edit']);

});
